stages:
  - build
  - deploy

.branch-rules: &branch-rules
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  <<: *branch-rules
  stage: build
  image: texlive/texlive:latest
  script:
    - make cv
    - ls -la ./build/
  artifacts:
    paths:
      - build/*.pdf

pages:
  <<: *branch-rules
  stage: deploy
  image: golang:alpine3.22
  script:
    - apk add --no-cache make
    - make page
  dependencies:
    - build
  pages: true
  artifacts:
    paths:
      - public
