stages:
  - build
  - deploy

.common: &common
  rules:
    - when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "src/**/*.tex"

build:
  <<: *common
  stage: build
  image: texlive/texlive:latest
  script:
    - make cv
    - ls -la ./build/
  artifacts:
    paths:
      - build/*.pdf

pages:
  <<: *common
  stage: deploy
  image: golang:alpine3.22
  script:
    - apk add --no-cache make
    - make page
  dependencies:
    - build
  pages: true
  artifacts:
    paths:
      - public
